version: '3.5'
services:
  openlink-virtuoso:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../datasets/musicbrainz-20131125:/usr/share/proj/musicbrainz
    ports:
      - 1111:1111
      - 8890:8890
