version: '3.5'
services:
  openlink-virtuoso:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../datasets/internal:/usr/share/proj/datasets
    ports:
      - 1111:1111
      - 8890:8890
